# ─── PayFlow ConfigMap + Secret ───────────────────────────────────────────────
# Apply: kubectl apply -f k8s/config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payflow-config
  namespace: payflow
data:
  # Infrastructure Hosts
  DB_HOST:                 "postgres"
  DB_PORT:                 "5432"
  DB_USER:                 "fintech"
  DB_NAME:                 "payflow"
  REDIS_HOST:              "redis"
  REDIS_PORT:              "6379"
  RABBITMQ_HOST:           "rabbitmq"
  RABBITMQ_PORT:           "5672"
  RABBITMQ_USER:           "fintech"
  MONGO_HOST:              "mongodb"
  MONGO_PORT:              "27017"
  MONGO_USER:              "fintech"
  MONGO_DB:                "payflow"
  # Connection URLs
  DATABASE_URL:            "postgres://fintech:fintech123@postgres:5432/payflow?sslmode=disable"
  DB_URL:                  "postgres://fintech:fintech123@postgres:5432/payflow?sslmode=disable"
  REDIS_URL:               "redis:6379"
  REDIS_ADDR:              "redis:6379"
  RABBITMQ_URL:            "amqp://fintech:rabbit123@rabbitmq:5672/"
  # Service Endpoints
  AUTH_SERVICE_URL:        "http://payflow-auth-service:8081"
  USER_KYC_SERVICE_URL:    "http://payflow-user-kyc-service:8082"
  ACCOUNT_SERVICE_URL:     "http://payflow-account-service:8083"
  TRANSACTION_SERVICE_URL: "http://payflow-transaction-service:8084"
  LEDGER_SERVICE_URL:      "http://payflow-ledger-service:8085"
  PAYMENT_CONNECTOR_URL:   "http://payflow-payment-connector:8086"
  NOTIFICATION_SERVICE_URL: "http://payflow-notification-service:8087"
  AUDIT_SERVICE_URL:       "http://payflow-audit-compliance:8088"
  # Observability
  TEMPO_ENDPOINT:          "jaeger:4317"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  GIN_MODE:                "release"

---
apiVersion: v1
kind: Secret
metadata:
  name: payflow-secrets
  namespace: payflow
type: Opaque
stringData:
  DB_PASSWORD:       "fintech123"
  RABBITMQ_PASSWORD: "rabbit123"
  MONGO_PASSWORD:    "mongo123"
  JWT_SECRET:        "supersecretkey123"
